version: '2'
services:
  testrpc:
    build: testrpc/
    command: --account="0xc7e1dd34128a2f4df8da145ae9f3824d15cecdf84ff28061546e951eb55ee8fd,1000"
  ## TODO: merge web3, frontend and fprint-service into a single image and run central service
  web3:
    build: web3/
    command: node index.js
    volumes:
      - ./web3/:/app
    working_dir: /app
    links:
      - testrpc:testrpc
    ports:
      - 3000:3000
  fprint-service:
    build: fingerprinting-service/
    ports:
      - 8080:8080
    volumes:
      - ./fingerprinting-service/:/app
  ## TODO: add monitor code and continue image here
  # monitor:
  #   image: fprint-monitor
